language: swift
osx_image: xcode9.3

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

cache:
  - cocoapods
  - bundler

before_install:
  - brew update
  - gem install cocoapods
  - pod install --repo-update
  - brew install swiftlint || true

before_script:
  - bundle exec danger

script:
  - set -o pipefail
  - xcodebuild -workspace Trust.xcworkspace -scheme Trust -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE" test | xcpretty

notifications:
  slack: trust-wallet:33Vj3pGpKoBMTBAHTB8dF79n
  email: false
